pid:
  kp:
    x: 0.1
    y: 0.1
    yaw: 0.2
  kd:
    x: 0.05
    y: 0.05
    yaw: 0.01
  ki:
    x: 0.01
    y: 0.05
    yaw: 0.001
  i_clamp:
    x: 0.1
    y: 0.1
    yaw: 0.01
  lookahead: 100
  time_to_wait: 100
  correction_threshold: 0.25
  pos_err_thresh: 0.3
  rot_err_thresh: 0.1
  path_debug: False
